import './global.css';
import AuthProvider from '../components/AuthProvider';
import RealtimeProvider from '../components/RealtimeProvider';

export const metadata = {
  title: 'Welcome to ',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <RealtimeProvider>{children}</RealtimeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
